import numpy as np

J = 0.99
N_BEST_TOURNAMENTS_FOR_PLAYER_RATING = 7
MAX_BONUS = 2300  # А.3.4
TEAMS_COUNT_FOR_BP = 15  # А.3.4
NEW_TEAMS_LOWERING_COEFFICIENT = 0.8  # A.3.12
TOP_TEAMS_FOR_Q_CALCULATION = 100  # A.3.11
PLAYERS_IN_TEAM_FOR_Q_CALCULATION = 6  # A.3.11
D2_MULTIPLIER = 300  # A.3.6
D2_EXPONENT_DENOMINATOR = 350  # A.3.6
D1_NEGATIVE_LOWERING_COEFFICIENT = 1  # A.3.6
MIN_TOURNAMENT_TO_RELEASE_RATING_RATIO = 0.5
MIN_PLAYERS_FOR_HEREDITY = 4  # A.3.2
MIN_PLAYERS_FOR_HEREDITY_OLD = 4
MIN_PLAYERS_FOR_HEREDITY_WITH_NAME_OLD = 3
MIN_LEGIONNAIRES_TO_REDUCE_BONUS = 3
REGULAR_TOURNAMENT_COEFFICIENT = 1  # A.3.6
STRICT_SYNCHRONOUS_TOURNAMENT_COEFFICIENT = 2./3.  # A.3.6
SYNCHRONOUS_TOURNAMENT_COEFFICIENT = 0.5  # A.3.6
TECHNICAL_RATING_RELEVANT_PLAYERS = 6
TECHNICAL_RATING_DISTRIBUTION = np.arange(6, 0, -1) / 6
